if(NOT DEFINED NATIVE_CACHE OR NOT DEFINED RUST_TOOLCHAIN OR NOT DEFINED TOKENIZER_DIR OR NOT DEFINED DESTINATION)
  message(FATAL_ERROR "Native cache, Rust toolchain, tokenizer, and writable license destination are required.")
endif()
file(MAKE_DIRECTORY "${DESTINATION}")
file(COPY "${NATIVE_CACHE}/licenses/" DESTINATION "${DESTINATION}"
     PATTERN "MLX-LICENSE" EXCLUDE)
file(GLOB_RECURSE candidates LIST_DIRECTORIES false "${NATIVE_CACHE}/cargo/registry/src/*")
foreach(source IN LISTS candidates)
  get_filename_component(name "${source}" NAME)
  if(name MATCHES "^(LICENSE|LICENCE|COPYING|COPYRIGHT|NOTICE|UNLICENSE)([.-].*)?$")
    file(RELATIVE_PATH relative "${NATIVE_CACHE}/cargo/registry/src" "${source}")
    get_filename_component(directory "${relative}" DIRECTORY)
    file(MAKE_DIRECTORY "${DESTINATION}/rust-crates/${directory}")
    file(COPY "${source}" DESTINATION "${DESTINATION}/rust-crates/${directory}")
  endif()
endforeach()
set(rust_docs "${RUST_TOOLCHAIN}/share/doc/rust")
if(NOT EXISTS "${rust_docs}/COPYRIGHT-library.html")
  message(FATAL_ERROR "Rust standard library copyright notices are missing.")
endif()
file(MAKE_DIRECTORY "${DESTINATION}/rust-stdlib")
file(COPY "${rust_docs}/COPYRIGHT-library.html" "${rust_docs}/licenses"
     DESTINATION "${DESTINATION}/rust-stdlib")
file(COPY "${TOKENIZER_DIR}/Cargo.lock" DESTINATION "${DESTINATION}")
# Platform crates (Candle on Linux) ship their lock file as <crate>.lock.
foreach(lock IN LISTS EXTRA_CARGO_LOCKS)
  get_filename_component(crate "${lock}" DIRECTORY)
  get_filename_component(crate "${crate}" NAME)
  file(COPY_FILE "${lock}" "${DESTINATION}/${crate}.lock")
endforeach()
