if(NOT DEFINED NATIVE_CACHE OR NOT DEFINED TOKENIZER_DIR OR NOT DEFINED DESTINATION)
  message(FATAL_ERROR "Native cache, tokenizer, and writable license destination are required.")
endif()
file(MAKE_DIRECTORY "${DESTINATION}")
file(COPY "${NATIVE_CACHE}/licenses/" DESTINATION "${DESTINATION}"
     PATTERN "MLX-LICENSE" EXCLUDE)
file(GLOB_RECURSE candidates LIST_DIRECTORIES false "${NATIVE_CACHE}/cargo/registry/src/*")
foreach(source IN LISTS candidates)
  get_filename_component(name "${source}" NAME)
  if(name MATCHES "^(LICENSE|LICENCE|COPYING|COPYRIGHT|NOTICE|UNLICENSE)([.-].*)?$")
    file(RELATIVE_PATH relative "${NATIVE_CACHE}/cargo/registry/src" "${source}")
    get_filename_component(directory "${relative}" DIRECTORY)
    file(MAKE_DIRECTORY "${DESTINATION}/rust-crates/${directory}")
    file(COPY "${source}" DESTINATION "${DESTINATION}/rust-crates/${directory}")
  endif()
endforeach()
set(rust_docs "${NATIVE_CACHE}/rustup/toolchains/1.90.0-aarch64-apple-darwin/share/doc/rust")
if(NOT EXISTS "${rust_docs}/COPYRIGHT-library.html")
  message(FATAL_ERROR "Rust standard library copyright notices are missing.")
endif()
file(MAKE_DIRECTORY "${DESTINATION}/rust-stdlib")
file(COPY "${rust_docs}/COPYRIGHT-library.html" "${rust_docs}/licenses"
     DESTINATION "${DESTINATION}/rust-stdlib")
file(COPY "${TOKENIZER_DIR}/Cargo.lock" DESTINATION "${DESTINATION}")
